name = "TriangulatedWindingNumbers"
uuid = "73cb218b-8b32-4ab2-aa8b-a5b1bf36c102"
authors = ["James Cook <cookjws@gmail.com>"]
version = "0.1.0"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
